# Generated by Django 4.1 on 2022-09-19 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="Topic Name"
                    ),
                ),
                (
                    "time",
                    models.IntegerField(
                        choices=[
                            (5, "5 Mins"),
                            (10, "10 Mins"),
                            (15, "15 Mins"),
                            (20, "20 Mins"),
                            (25, "25 Mins"),
                            (30, "30 Mins"),
                            (35, "35 Mins"),
                            (40, "40 Mins"),
                            (45, "45 Mins"),
                            (50, "50 Mins"),
                            (55, "55 Mins"),
                            (60, "60 Mins"),
                        ],
                        verbose_name="Total test time in minutes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Results",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField()),
                ("date_time", models.DateTimeField(auto_now=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="quizApp.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-date_time"],},
        ),
        migrations.CreateModel(
            name="QuestionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("option_1", models.CharField(max_length=200)),
                ("option_2", models.CharField(max_length=200)),
                ("option_3", models.CharField(max_length=200)),
                ("option_4", models.CharField(max_length=200)),
                (
                    "correct_option",
                    models.CharField(
                        choices=[("1", 1), ("2", 2), ("3", 3), ("4", 4)], max_length=200
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quizApp.topic",
                    ),
                ),
            ],
        ),
    ]
